name: get advisories

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependency check
      if: runner.os == 'Linux'
      run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev lld
    - name: dependency check
      if: runner.os == 'windows'
      run: | 
        cargo install -f cargo-binutils
        rustup component add llvm-tools-preview
    - name: dependency check
      if: runner.os == 'macos'
      run: brew update && brew install michaeleisel/zld/zld && brew install gcc && brew upgrade
    - name: rustup install
      run: | 
        rustup toolchain install nightly
        rustup update
        rustup default nightly
    - name: install cargo deny
      run: cargo install --locked cargo-deny
    - name: check advisories
      run: cargo deny check advisories
